project:
  type: website
  output-dir: docs

website:
  title: "template"

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Motivation

      - href: lesson5.qmd
        text: "Chapter 5: Building a Subway Surfer Clone"

      - href: lesson6.qmd
        text: "Chapter 6: Obstacles and Collision"

      - href: lesson7.qmd
        text: "Chapter 7: Scoring and Sound"

      - href: lesson8.qmd
        text: "Lesson 8: Customization and Polish"
      
      - href: Lesson9.qmd
        text: "Lesson 9: Simple Platformer Gravity and Jumping"

      - href: Lesson10.qmd
        text: "Lesson 10: Simple Platformer - Platforms and Collision"

      - href: Lesson11.qmd
        text: "Enemies and Collectibles: Adding Risk and Reward"
      
      - href: Lesson12.qmd
        text: "Chapter 12: Level Design and Polish"



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
